version: '3'
services:
  app1: 
    build: ./app1
    ports:
      - "5001:5000"    
  app2:
    build: ./app2
    ports:
      - "5002:5000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - app1
      - app2
